---
title: "Designing a map with R and OpenStreetMap"
output: html_notebook
author: "Evgeny Politov"
date: "September 9, 2023"
---

## Load packages

```{r}
library(sf)
library(ggplot2)
library(dplyr)
library(osmdata)
library(crsuggest)
library(sysfonts)
library(showtext)
```

## Prepare the query 
```{r}
#define your midpoint coordinates and radius
lat <- 55.753846 
lon <- 37.620935
r <- 10000
crs <- 4326

midpoint <- st_point(c(lon,lat)) %>% 
  st_sfc()%>% 
  st_set_crs(crs)

circle_mask <- st_buffer(midpoint, dist = r)

#define the bounding box for overpass query 
bbox <- st_bbox(circle_mask) 

#set API call
query <- opq(bbox = bbox)

```


## Pull Data

```{r}

#  Water layer
water <- query %>% 
  add_osm_feature(key = "natural",
                  value = "water") %>% 
  osmdata_sf()

# Roads layer
pedestrian <- query %>% 
  add_osm_feature(key = "highway",
                  value = c("footway", "pedestrian")) %>%
  osmdata_sf() 
  
minor_roads <- query %>% 
  add_osm_feature(key = "highway",
                  value = c("secondary","tertiary",
                            "residential","trunk_link",
                            "primary_link","motorway_link",
                            "secondary_link","tertiary_link")) %>%
  osmdata_sf()
  
main_roads <- query %>% 
  add_osm_feature(key = "highway",
                  value = c("primary","trunk","motorway"))%>%
  osmdata_sf()

# Woods layer
woods <- query %>% 
  add_osm_features(list(
    "natural" = "wood",
    "leisure" = "park")) %>% 
  osmdata_sf()
```

## Examine the datasets and plot samples

If needed add/remove features and re-run queries

```{r}
ggplot() +
  geom_sf(data = water$osm_multipolygons,
          color = NA,
          fill = "steelblue")+
  
  geom_sf(data = woods$osm_multipolygons,
          color= NA)+
  
  geom_sf(data = pedestrian$osm_lines,
          color = "purple")+

  geom_sf(data = minor_roads$osm_lines,
          color = "blue")+

  geom_sf(data = main_roads$osm_lines,
          color = "violet")+
  
  geom_sf(data = circle_mask,
          fill = NA,
          color = "red")+
  
  theme_void()


```
## Set the right Coordinate Reference System

```{r}
# pull the list of suggested EPSG projections for your midpoint coordinates
# alternatively you can use any of your loaded OSM geometries
suggest_crs(midpoint)
```


```{r}
#convert all layers to the appropriate CRS and trim to mask
plot_crs <- 2705
midpoint <- midpoint %>% st_transform(crs = plot_crs)
circle_mask <- st_buffer(midpoint, dist = r)

water <- water$osm_multipolygons %>%
  st_transform(crs = plot_crs) %>% 
  st_intersection(circle_mask)

woods <- woods$osm_multipolygons %>% 
  st_make_valid() %>% #add in case you face 'geom is invalid' error
  st_transform(crs = plot_crs) %>% 
  st_intersection(circle_mask)

pedestrian <- pedestrian$osm_lines %>%
  st_transform(crs = plot_crs) %>% 
  st_intersection(circle_mask)

minor_roads <- minor_roads$osm_lines %>%
  st_transform(crs = plot_crs) %>% 
  st_intersection(circle_mask)

main_roads <- main_roads$osm_lines %>%
  st_transform(crs = plot_crs) %>% 
  st_intersection(circle_mask)

```
## Plot the results

```{r}
#set your color palette
background_fill <-"#292929"
woods_fill <-"#7cb9a3"
key_color <- "#dcdcdc"
water_fill <- "#39b9b4"


#add fonts
font_add_google("Poiret One", "poiret")  
showtext_auto()

#Plot
circle_map <- ggplot()+
  
  geom_sf(data = circle_mask,
          fill = background_fill,
          color = NA)+
 
  #water
  geom_sf(data = water,
          fill = water_fill,
          color = NA
          )+
  
  #woods
  geom_sf(data = woods,
          fill = woods_fill,
          color = NA)+
  
  #roads
  geom_sf(data = pedestrian,
          color= key_color,
          linewidth = .3,
          alpha = .3
          )+
  
  geom_sf(data = minor_roads,
          color = key_color,
          linewidth = .4,
          alpha = .8
          )+
  
  geom_sf(data = main_roads,
          color= key_color,
          linewidth = .8
          )+
  geom_sf(data = circle_mask,
          fill = NA,
          color = key_color,
          linewidth = .8)+
  
  labs(caption = "Moscow")+
   theme_void()+

   
    theme(plot.caption = element_text(family = "poiret", 
                                    color = key_color,
                                    size=24,
                                    hjust=0.5),
          plot.margin = unit(c(0.5,0.7,0.5,0.7),"in"),
          plot.background = element_rect(fill = background_fill,
                                         color = NA))

circle_map
```

## Save the result
```{r}

ggsave("city_map.png", plot = last_plot(),
       scale = 1, width = 1500, height = 1500, units = "px",
       dpi = 300)
```

